import React from 'react'
import '../styles/style.scss'
const Report = () => {
  return (
    <div>
        <main className='home'>
            <div className="content">
                <p>Report generated by AI</p>
            </div>
        </main>
    </div>
  )
}

export default Report